name: Action test
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run:
          lsb_release -a
          echo "> ls /etc/apt/sources.list.d/"
          ls /etc/apt/sources.list.d/
          echo "cat "/etc/apt/sources.list"
          cat /etc/apt/sources.list