name: build x86_64
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Install Dependencies
        run: |
          cp buildozer.spec buildozer_template.spec
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build x86_64
        run: |
          python libs/writer.py x86_64
      - name: Sign APKs
        run: |
          export apksigner_path="$(find ~/.buildozer/android/platform/android-sdk | grep apksigner | head -n 1)"
          ls libs
          pwd
          bash $apksigner_path sign --ks libs/cfapp.jks --ks-key-alias cf3012 --ks-pass pass:$( python libs/echo.pyc ) --key-pass pass:$( python libs/echo.pyc ) --v1-signing-enabled --v2-signing-enabled bin/*.apk
      - name: Verify Signatures
        continue-on-error: true
        run: |
          export apksigner_path="$(find ~/.buildozer/android/platform/android-sdk | grep apksigner | head -n 1)"
          for f in bin/*.apk; do
            echo "Verifying $f"
            $apksigner_path verify --print-certs $f
      - name: Upload Artifacts
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: Release x86_64 0.1
          path: 'bin/*'
